#221 adressenregister migratie
OnroerendErfgoed/actoren_widget pull request #222
Opened 2023-10-27 09:07 UTC by roefem

2023-10-27 09:08 UTC, roefem commented
Ik heb ook ineens maar de oude code gedumpt, volgens wat ik zie wordt enkel maar de app folder nog gebruikt in dojo projecten

2023-10-27 15:06 UTC, cedrikv reviewed
indien mogelijk test/widget/test_newActorWidgetInDialog.html nog laten staan, en zien dat hij nog werkt.
in pycharm kan die gebruikt worden om snel te testen, rechts klikken op de html file en "run" kiezen

2023-10-30 10:25 UTC, pegahmoh requested changes
Search params in advanced search ook nog updaten. (
`gemeente_naam` => gemeente, `straat_naam` => straat, `huisnummer_label` => huisnummer, `subadres` => busnummer)
https://github.com/OnroerendErfgoed/actoren_widget/blob/89951936096d76da33d15f6b76ba881f08b4c046/app/widgets/AdvSearch.js#L107

2023-10-31 14:24 UTC, pegahmoh approved these changes

2023-10-31 14:36 UTC, merged